package common.zeroquest.entity.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.MathHelper;

public class ModelJakanPrime extends ModelBase
{
  //fields
    ModelRenderer LWPart1;
    ModelRenderer LWPart2;
    ModelRenderer LWPart3;
    ModelRenderer LWPart4;
    ModelRenderer LWPart5;
    ModelRenderer LWPart6;
    ModelRenderer LWWeb1;
    ModelRenderer LWWeb2;
    ModelRenderer LWWeb3;
    ModelRenderer LWWeb4;
    ModelRenderer LWWeb5;
    ModelRenderer LWWeb6;
    ModelRenderer LWPart7;
    ModelRenderer RWPart1;
    ModelRenderer RWPart2;
    ModelRenderer RWPart3;
    ModelRenderer RWPart4;
    ModelRenderer RWPart5;
    ModelRenderer RWPart6;
    ModelRenderer RWPart7;
    ModelRenderer RWWeb1;
    ModelRenderer RWWeb2;
    ModelRenderer RWWeb3;
    ModelRenderer RWWeb4;
    ModelRenderer RWWeb5;
    ModelRenderer RWWeb6;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer THorn1;
    ModelRenderer THorn2;
    ModelRenderer Horn3;
    ModelRenderer Horn2;
    ModelRenderer Horn1;
    ModelRenderer Head;
    ModelRenderer Snout1;
    ModelRenderer Snout2;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer Torso;
    ModelRenderer BLLeg1;
    ModelRenderer BLLeg2;
    ModelRenderer BRLeg1;
    ModelRenderer BRLeg2;
    ModelRenderer FLLeg1;
    ModelRenderer FLLeg2;
    ModelRenderer FRLeg1;
    ModelRenderer FRLeg2;
  
  public ModelJakanPrime()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      LWPart1 = new ModelRenderer(this, 0, 40);
      LWPart1.addBox(0F, 0F, 0F, 10, 1, 1);
      LWPart1.setRotationPoint(3F, 12.3F, -6F);
      LWPart1.setTextureSize(128, 64);
      LWPart1.mirror = true;
      setRotation(LWPart1, 0F, 0F, 0F);
      LWPart2 = new ModelRenderer(this, 0, 42);
      LWPart2.addBox(9F, 0F, 1F, 2, 1, 1);
      LWPart2.setRotationPoint(3F, 12.3F, -6F);
      LWPart2.setTextureSize(128, 64);
      LWPart2.mirror = true;
      setRotation(LWPart2, 0F, 0F, 0F);
      LWPart3 = new ModelRenderer(this, 0, 42);
      LWPart3.addBox(10F, 0F, 2F, 2, 1, 1);
      LWPart3.setRotationPoint(3F, 12.3F, -6F);
      LWPart3.setTextureSize(128, 64);
      LWPart3.mirror = true;
      setRotation(LWPart3, 0F, 0F, 0F);
      LWPart4 = new ModelRenderer(this, 7, 42);
      LWPart4.addBox(11F, 0F, 3F, 1, 1, 2);
      LWPart4.setRotationPoint(3F, 12.3F, -6F);
      LWPart4.setTextureSize(128, 64);
      LWPart4.mirror = true;
      setRotation(LWPart4, 0F, 0F, 0F);
      LWPart5 = new ModelRenderer(this, 0, 44);
      LWPart5.addBox(12F, 0F, 4F, 1, 1, 1);
      LWPart5.setRotationPoint(3F, 12.3F, -6F);
      LWPart5.setTextureSize(128, 64);
      LWPart5.mirror = true;
      setRotation(LWPart5, 0F, 0F, 0F);
      LWPart6 = new ModelRenderer(this, 11, 42);
      LWPart6.addBox(13F, 0F, 4F, 1, 1, 3);
      LWPart6.setRotationPoint(3F, 12.3F, -6F);
      LWPart6.setTextureSize(128, 64);
      LWPart6.mirror = true;
      setRotation(LWPart6, 0F, 0F, 0F);
      LWWeb1 = new ModelRenderer(this, 13, 47);
      LWWeb1.addBox(0F, 0.5F, 1F, 5, 0, 3);
      LWWeb1.setRotationPoint(3F, 12.3F, -6F);
      LWWeb1.setTextureSize(128, 64);
      LWWeb1.mirror = true;
      setRotation(LWWeb1, 0F, 0F, 0F);
      LWWeb2 = new ModelRenderer(this, 21, 45);
      LWWeb2.addBox(5F, 0.5F, 1F, 2, 0, 6);
      LWWeb2.setRotationPoint(3F, 12.3F, -6F);
      LWWeb2.setTextureSize(128, 64);
      LWWeb2.mirror = true;
      setRotation(LWWeb2, 0F, 0F, 0F);
      LWWeb3 = new ModelRenderer(this, 8, 51);
      LWWeb3.addBox(7F, 0.5F, 1F, 2, 0, 8);
      LWWeb3.setRotationPoint(3F, 12.3F, -6F);
      LWWeb3.setTextureSize(128, 64);
      LWWeb3.mirror = true;
      setRotation(LWWeb3, 0F, 0F, 0F);
      LWWeb4 = new ModelRenderer(this, 22, 51);
      LWWeb4.addBox(9F, 0.5F, 2F, 2, 0, 10);
      LWWeb4.setRotationPoint(3F, 12.3F, -6F);
      LWWeb4.setTextureSize(128, 64);
      LWWeb4.mirror = true;
      setRotation(LWWeb4, 0F, 0F, 0F);
      LWWeb5 = new ModelRenderer(this, 27, 50);
      LWWeb5.addBox(11F, 0.5F, 5F, 2, 0, 10);
      LWWeb5.setRotationPoint(3F, 12.3F, -6F);
      LWWeb5.setTextureSize(128, 64);
      LWWeb5.mirror = true;
      setRotation(LWWeb5, 0F, 0F, 0F);
      LWWeb6 = new ModelRenderer(this, 11, 33);
      LWWeb6.addBox(12F, 0.5F, 7F, 2, 0, 11);
      LWWeb6.setRotationPoint(3F, 12.3F, -6F);
      LWWeb6.setTextureSize(128, 64);
      LWWeb6.mirror = true;
      setRotation(LWWeb6, 0F, 0F, 0F);
      LWPart7 = new ModelRenderer(this, 0, 47);
      LWPart7.addBox(14F, 0F, 6F, 1, 1, 14);
      LWPart7.setRotationPoint(3F, 12.3F, -6F);
      LWPart7.setTextureSize(128, 64);
      LWPart7.mirror = true;
      setRotation(LWPart7, 0F, 0F, 0F);
      RWPart1 = new ModelRenderer(this, 0, 40);
      RWPart1.addBox(0F, 0F, -1F, 10, 1, 1);
      RWPart1.setRotationPoint(-2F, 12.3F, -6F);
      RWPart1.setTextureSize(128, 64);
      RWPart1.mirror = true;
      setRotation(RWPart1, 0F, -3.141593F, 0F);
      RWPart2 = new ModelRenderer(this, 0, 42);
      RWPart2.addBox(9F, 0F, -2F, 2, 1, 1);
      RWPart2.setRotationPoint(-2F, 12.3F, -6F);
      RWPart2.setTextureSize(128, 64);
      RWPart2.mirror = true;
      setRotation(RWPart2, 0F, -3.141593F, 0F);
      RWPart3 = new ModelRenderer(this, 0, 42);
      RWPart3.addBox(10F, 0F, -3F, 2, 1, 1);
      RWPart3.setRotationPoint(-2F, 12.3F, -6F);
      RWPart3.setTextureSize(128, 64);
      RWPart3.mirror = true;
      setRotation(RWPart3, 0F, -3.141593F, 0F);
      RWPart4 = new ModelRenderer(this, 7, 42);
      RWPart4.addBox(11F, 0F, -5F, 1, 1, 2);
      RWPart4.setRotationPoint(-2F, 12.3F, -6F);
      RWPart4.setTextureSize(128, 64);
      RWPart4.mirror = true;
      setRotation(RWPart4, 0F, -3.141593F, 0F);
      RWPart5 = new ModelRenderer(this, 0, 44);
      RWPart5.addBox(12F, 0F, -5F, 1, 1, 1);
      RWPart5.setRotationPoint(-2F, 12.3F, -6F);
      RWPart5.setTextureSize(128, 64);
      RWPart5.mirror = true;
      setRotation(RWPart5, 0F, -3.141593F, 0F);
      RWPart6 = new ModelRenderer(this, 11, 42);
      RWPart6.addBox(13F, 0F, -7F, 1, 1, 3);
      RWPart6.setRotationPoint(-2F, 12.3F, -6F);
      RWPart6.setTextureSize(128, 64);
      RWPart6.mirror = true;
      setRotation(RWPart6, 0F, -3.141593F, 0F);
      RWPart7 = new ModelRenderer(this, 0, 47);
      RWPart7.addBox(14F, 0F, -20F, 1, 1, 14);
      RWPart7.setRotationPoint(-2F, 12.3F, -6F);
      RWPart7.setTextureSize(128, 64);
      RWPart7.mirror = true;
      setRotation(RWPart7, 0F, -3.141593F, 0F);
      RWWeb1 = new ModelRenderer(this, 13, 47);
      RWWeb1.addBox(0F, 0.5F, -4F, 5, 0, 3);
      RWWeb1.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb1.setTextureSize(128, 64);
      RWWeb1.mirror = true;
      setRotation(RWWeb1, 0F, -3.141593F, 0F);
      RWWeb2 = new ModelRenderer(this, 21, 45);
      RWWeb2.addBox(5F, 0.5F, -7F, 2, 0, 6);
      RWWeb2.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb2.setTextureSize(128, 64);
      RWWeb2.mirror = true;
      setRotation(RWWeb2, 0F, -3.141593F, 0F);
      RWWeb3 = new ModelRenderer(this, 8, 51);
      RWWeb3.addBox(7F, 0.5F, -9F, 2, 0, 8);
      RWWeb3.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb3.setTextureSize(128, 64);
      RWWeb3.mirror = true;
      setRotation(RWWeb3, 0F, -3.141593F, 0F);
      RWWeb4 = new ModelRenderer(this, 22, 51);
      RWWeb4.addBox(9F, 0.5F, -12F, 2, 0, 10);
      RWWeb4.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb4.setTextureSize(128, 64);
      RWWeb4.mirror = true;
      setRotation(RWWeb4, 0F, -3.141593F, 0F);
      RWWeb5 = new ModelRenderer(this, 27, 50);
      RWWeb5.addBox(11F, 0.5F, -15F, 2, 0, 10);
      RWWeb5.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb5.setTextureSize(128, 64);
      RWWeb5.mirror = true;
      setRotation(RWWeb5, 0F, -3.141593F, 0F);
      RWWeb6 = new ModelRenderer(this, 11, 33);
      RWWeb6.addBox(12F, 0.5F, -18F, 2, 0, 11);
      RWWeb6.setRotationPoint(-2F, 12.3F, -6F);
      RWWeb6.setTextureSize(128, 64);
      RWWeb6.mirror = true;
      setRotation(RWWeb6, 0F, -3.141593F, 0F);
      Tail1 = new ModelRenderer(this, 35, 2);
      Tail1.addBox(-2.5F, 0F, 0F, 5, 5, 5);
      Tail1.setRotationPoint(0.5F, 12.5F, 5F);
      Tail1.setTextureSize(128, 64);
      Tail1.mirror = true;
      setRotation(Tail1, -0.3346145F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 56, 2);
      Tail2.addBox(-2F, -0.5F, 4F, 4, 4, 6);
      Tail2.setRotationPoint(0.5F, 12.5F, 5F);
      Tail2.setTextureSize(128, 64);
      Tail2.mirror = true;
      setRotation(Tail2, -0.5205064F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 71, 0);
      Tail3.addBox(-1.5F, 1F, 8F, 3, 3, 5);
      Tail3.setRotationPoint(0.5F, 12.5F, 5F);
      Tail3.setTextureSize(128, 64);
      Tail3.mirror = true;
      setRotation(Tail3, -0.4089706F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 83, 0);
      Tail4.addBox(-1F, 3.5F, 12F, 2, 2, 3);
      Tail4.setRotationPoint(0.5F, 12.5F, 5F);
      Tail4.setTextureSize(128, 64);
      Tail4.mirror = true;
      setRotation(Tail4, -0.2602562F, 0F, 0F);
      Tail5 = new ModelRenderer(this, 83, 0);
      Tail5.addBox(-1F, 6F, 13.8F, 2, 2, 3);
      Tail5.setRotationPoint(0.5F, 12.5F, 5F);
      Tail5.setTextureSize(128, 64);
      Tail5.mirror = true;
      setRotation(Tail5, -0.0860354F, 0F, 0F);
      THorn1 = new ModelRenderer(this, 0, 31);
      THorn1.addBox(1F, 6.5F, 15.8F, 1, 1, 6);
      THorn1.setRotationPoint(0.5F, 12.5F, 5F);
      THorn1.setTextureSize(128, 64);
      THorn1.mirror = true;
      setRotation(THorn1, -0.0860273F, 0F, 0F);
      THorn2 = new ModelRenderer(this, 0, 31);
      THorn2.addBox(-2F, 6.5F, 15.8F, 1, 1, 6);
      THorn2.setRotationPoint(0.5F, 12.5F, 5F);
      THorn2.setTextureSize(128, 64);
      THorn2.mirror = true;
      setRotation(THorn2, -0.0860273F, 0F, 0F);
      Horn3 = new ModelRenderer(this, 0, 31);
      Horn3.addBox(-1F, -1F, -10F, 1, 1, 6);
      Horn3.setRotationPoint(1F, 6F, -7F);
      Horn3.setTextureSize(128, 64);
      Horn3.mirror = true;
      setRotation(Horn3, 0F, 0F, 0F);
      Horn2 = new ModelRenderer(this, 0, 31);
      Horn2.addBox(1F, -1F, -8F, 1, 1, 6);
      Horn2.setRotationPoint(1F, 6F, -7F);
      Horn2.setTextureSize(128, 64);
      Horn2.mirror = true;
      setRotation(Horn2, 0F, 0F, 0F);
      Horn1 = new ModelRenderer(this, 0, 31);
      Horn1.addBox(-3F, -1F, -8F, 1, 1, 6);
      Horn1.setRotationPoint(1F, 6F, -7F);
      Horn1.setTextureSize(128, 64);
      Horn1.mirror = true;
      setRotation(Horn1, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 74, 31);
      Head.addBox(-3F, 0F, -12F, 5, 5, 5);
      Head.setRotationPoint(1F, 6F, -7F);
      Head.setTextureSize(128, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Snout1 = new ModelRenderer(this, 74, 42);
      Snout1.addBox(-2F, 2F, -15F, 3, 2, 3);
      Snout1.setRotationPoint(1F, 6F, -7F);
      Snout1.setTextureSize(128, 64);
      Snout1.mirror = true;
      setRotation(Snout1, 0F, 0F, 0F);
      Snout2 = new ModelRenderer(this, 87, 42);
      Snout2.addBox(-1.5F, 4F, -14F, 2, 1, 2);
      Snout2.setRotationPoint(1F, 6F, -7F);
      Snout2.setTextureSize(128, 64);
      Snout2.mirror = true;
      setRotation(Snout2, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 33, 13);
      Neck1.addBox(-3F, 0F, -4F, 5, 5, 7);
      Neck1.setRotationPoint(1F, 12F, -7F);
      Neck1.setTextureSize(128, 64);
      Neck1.mirror = true;
      setRotation(Neck1, -0.4089647F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 51, 19);
      Neck2.addBox(-2.5F, 1.833333F, -8.233334F, 4, 4, 7);
      Neck2.setRotationPoint(1F, 12F, -7F);
      Neck2.setTextureSize(128, 64);
      Neck2.mirror = true;
      setRotation(Neck2, -0.8551081F, 0F, 0F);
      Torso = new ModelRenderer(this, 0, 0);
      Torso.addBox(-3.5F, 0F, 0F, 7, 6, 12);
      Torso.setRotationPoint(0.5F, 12F, -7F);
      Torso.setTextureSize(128, 64);
      Torso.mirror = true;
      setRotation(Torso, 0F, 0F, 0F);
      BLLeg1 = new ModelRenderer(this, 0, 0);
      BLLeg1.addBox(0F, 0F, 0F, 2, 5, 3);
      BLLeg1.setRotationPoint(4F, 16F, 1F);
      BLLeg1.setTextureSize(128, 64);
      BLLeg1.mirror = true;
      setRotation(BLLeg1, 0F, 0F, 0F);
      BLLeg2 = new ModelRenderer(this, 0, 19);
      BLLeg2.addBox(0F, 3F, 3F, 2, 5, 3);
      BLLeg2.setRotationPoint(4F, 16F, 1F);
      BLLeg2.setTextureSize(128, 64);
      BLLeg2.mirror = true;
      setRotation(BLLeg2, 0F, 0F, 0F);
      BRLeg1 = new ModelRenderer(this, 0, 0);
      BRLeg1.addBox(0F, 0F, 0F, 2, 5, 3);
      BRLeg1.setRotationPoint(-5F, 16F, 1F);
      BRLeg1.setTextureSize(128, 64);
      BRLeg1.mirror = true;
      setRotation(BRLeg1, 0F, 0F, 0F);
      BRLeg2 = new ModelRenderer(this, 0, 19);
      BRLeg2.addBox(0F, 3F, 3F, 2, 5, 3);
      BRLeg2.setRotationPoint(-5F, 16F, 1F);
      BRLeg2.setTextureSize(128, 64);
      BRLeg2.mirror = true;
      setRotation(BRLeg2, 0F, 0F, 0F);
      FLLeg1 = new ModelRenderer(this, 27, 0);
      FLLeg1.addBox(0F, 0F, 0F, 2, 4, 2);
      FLLeg1.setRotationPoint(4F, 16.3F, -5F);
      FLLeg1.setTextureSize(128, 64);
      FLLeg1.mirror = true;
      setRotation(FLLeg1, 0F, 0F, 0F);
      FLLeg2 = new ModelRenderer(this, 11, 19);
      FLLeg2.addBox(-1F, 2.6F, -2F, 2, 5, 2);
      FLLeg2.setRotationPoint(5F, 16.3F, -5F);
      FLLeg2.setTextureSize(128, 64);
      FLLeg2.mirror = true;
      setRotation(FLLeg2, 0F, 0F, 0F);
      FRLeg1 = new ModelRenderer(this, 27, 0);
      FRLeg1.addBox(-2F, 0F, 0F, 2, 4, 2);
      FRLeg1.setRotationPoint(-3F, 16.3F, -5F);
      FRLeg1.setTextureSize(128, 64);
      FRLeg1.mirror = true;
      setRotation(FRLeg1, 0F, 0F, 0F);
      FRLeg2 = new ModelRenderer(this, 11, 19);
      FRLeg2.addBox(-2F, 2.6F, -2F, 2, 5, 2);
      FRLeg2.setRotationPoint(-3F, 16.3F, -5F);
      FRLeg2.setTextureSize(128, 64);
      FRLeg2.mirror = true;
      setRotation(FRLeg2, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
      super.render(par1Entity, par2, par3, par4, par5, par6, par7);
      this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);

      if (this.isChild)
      {
          float f6 = 2.0F;
  	    Horn1.render(par7);
  	    Horn2.render(par7);
  	    Horn3.render(par7);
  	    RWPart1.render(par7);
  	    RWPart2.render(par7);
  	    RWPart3.render(par7);
  	    RWPart4.render(par7);
  	    RWPart5.render(par7);
  	    RWPart6.render(par7);
  	    RWPart7.render(par7);
  	    RWWeb1.render(par7);
  	    RWWeb2.render(par7);
  	    RWWeb3.render(par7);
  	    RWWeb4.render(par7);
  	    RWWeb5.render(par7);
  	    RWWeb6.render(par7);
  	    LWPart1.render(par7);
  	    LWPart2.render(par7);
  	    LWPart3.render(par7);
  	    LWPart4.render(par7);
  	    LWPart5.render(par7);
  	    LWPart6.render(par7);
  	    LWPart7.render(par7);
  	    LWWeb1.render(par7);
  	    LWWeb2.render(par7);
  	    LWWeb3.render(par7);
  	    LWWeb4.render(par7);
  	    LWWeb5.render(par7);
  	    LWWeb6.render(par7);
  	    Head.render(par7);
  	    Snout2.render(par7);
  	    Snout1.render(par7);
  	    Neck2.renderWithRotation(par7);
  	    Neck1.renderWithRotation(par7);
  	    Torso.render(par7);
  	    FLLeg1.render(par7);
  	    FLLeg2.render(par7);
  	    FRLeg1.render(par7);
  	    FRLeg2.render(par7);
  	    BLLeg1.render(par7);
  	    BLLeg2.render(par7);
  	    BRLeg1.render(par7);
  	    BRLeg2.render(par7);
  	    Tail1.renderWithRotation(par7);
  	    Tail2.renderWithRotation(par7);
  	    Tail3.renderWithRotation(par7);
  	    Tail4.renderWithRotation(par7);
  	    Tail5.renderWithRotation(par7);
  	    THorn1.renderWithRotation(par7);
  	    THorn2.renderWithRotation(par7);
      }
      else
      {
          GL11.glPushMatrix();
          GL11.glScalef(2.6F, 2.6F, 2.6F);
          GL11.glTranslatef(0.0F, -0.9F, 0.0F);
  	    Horn1.render(par7);
  	    Horn2.render(par7);
  	    Horn3.render(par7);
  	    RWPart1.render(par7);
  	    RWPart2.render(par7);
  	    RWPart3.render(par7);
  	    RWPart4.render(par7);
  	    RWPart5.render(par7);
  	    RWPart6.render(par7);
  	    RWPart7.render(par7);
  	    RWWeb1.render(par7);
  	    RWWeb2.render(par7);
  	    RWWeb3.render(par7);
  	    RWWeb4.render(par7);
  	    RWWeb5.render(par7);
  	    RWWeb6.render(par7);
  	    LWPart1.render(par7);
  	    LWPart2.render(par7);
  	    LWPart3.render(par7);
  	    LWPart4.render(par7);
  	    LWPart5.render(par7);
  	    LWPart6.render(par7);
  	    LWPart7.render(par7);
  	    LWWeb1.render(par7);
  	    LWWeb2.render(par7);
  	    LWWeb3.render(par7);
  	    LWWeb4.render(par7);
  	    LWWeb5.render(par7);
  	    LWWeb6.render(par7);
  	    Head.render(par7);
  	    Snout2.render(par7);
  	    Snout1.render(par7);
  	    Neck2.renderWithRotation(par7);
  	    Neck1.renderWithRotation(par7);
  	    Torso.render(par7);
  	    FLLeg1.renderWithRotation(par7);
  	    FLLeg2.renderWithRotation(par7);
  	    FRLeg1.renderWithRotation(par7);
  	    FRLeg2.renderWithRotation(par7);
  	    BLLeg1.renderWithRotation(par7);
  	    BLLeg2.renderWithRotation(par7);
  	    BRLeg1.renderWithRotation(par7);
  	    BRLeg2.renderWithRotation(par7);
  	    Tail1.renderWithRotation(par7);
  	    Tail2.renderWithRotation(par7);
  	    Tail3.renderWithRotation(par7);
  	    Tail4.renderWithRotation(par7);
  	    Tail5.renderWithRotation(par7);
  	    THorn1.renderWithRotation(par7);
  	    THorn2.renderWithRotation(par7);
          GL11.glPopMatrix();
      }
  }

  /**
   * Used for easily adding entity-dependent animations. The second and third float params here are the same second
   * and third as in the setRotationAngles method.
   */
  public void setLivingAnimations(EntityLivingBase par1EntityLivingBase, float par2, float par3, float par4)
  {	
  	
      	this.Torso.setRotationPoint(0.5F, 13F, -7F);
      	this.Torso.rotateAngleX = par3 / (180F / (float)Math.PI);
      	
          this.BRLeg1.rotateAngleX = MathHelper.cos(par2 * 0.6662F + (float)Math.PI) * 1.4F * par3;
          this.FRLeg1.rotateAngleX = MathHelper.cos(par2 * 0.6662F + (float)Math.PI) * 1.4F * par3;
          this.BRLeg2.rotateAngleX = MathHelper.cos(par2 * 0.6662F + (float)Math.PI) * 1.4F * par3;
          this.FRLeg2.rotateAngleX = MathHelper.cos(par2 * 0.6662F + (float)Math.PI) * 1.4F * par3;
          this.BLLeg1.rotateAngleX = MathHelper.cos(par2 * 0.6662F) * 1.4F * par3;
          this.FLLeg1.rotateAngleX = MathHelper.cos(par2 * 0.6662F) * 1.4F * par3;
          this.BLLeg2.rotateAngleX = MathHelper.cos(par2 * 0.6662F) * 1.4F * par3;
          this.FLLeg2.rotateAngleX = MathHelper.cos(par2 * 0.6662F) * 1.4F * par3;
          
          this.Tail1.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.455F * par3;
          this.Tail2.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.454F * par3;
          this.Tail3.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.453F * par3;
          this.Tail4.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.452F * par3;
          this.Tail5.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.451F * par3;
          this.THorn1.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.451F * par3;
          this.THorn2.rotateAngleY = MathHelper.cos(par2 * 0.6662F) * 1.451F * par3;

  }

  /**
   * Sets the model's various rotation angles. For bipeds, par1 and par2 are used for animating the movement of arms
   * and legs, where par1 represents the time(so that arms and legs swing back and forth) and par2 represents how
   * "far" arms and legs can swing at most.
   */
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
      this.Head.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Head.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Snout1.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Snout1.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Snout2.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Snout2.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Horn1.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Horn1.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Horn2.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Horn2.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Horn3.rotateAngleX = par5 / (280F / (float)Math.PI);
      this.Horn3.rotateAngleY = par4 / (180F / (float)Math.PI);
      
	  this.Neck2.setRotationPoint(1F, 13F, -7F);
	  this.Neck1.setRotationPoint(1F, 13F, -7F);
      this.Neck1.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Neck2.rotateAngleY = par4 / (180F / (float)Math.PI);
      
      /*this.RWPart1.rotateAngleZ = par3;
      this.RWPart2.rotateAngleZ = par3;
      this.RWPart3.rotateAngleZ = par3;
      this.RWPart4.rotateAngleZ = par3;
      this.RWPart5.rotateAngleZ = par3;
      this.RWPart6.rotateAngleZ = par3;
      this.RWPart7.rotateAngleZ = par3;
      this.RWWeb1.rotateAngleZ = par3;
      this.RWWeb2.rotateAngleZ = par3;
      this.RWWeb3.rotateAngleZ = par3;
      this.RWWeb4.rotateAngleZ = par3;
      this.RWWeb5.rotateAngleZ = par3;
      this.RWWeb6.rotateAngleZ = par3;
      this.LWPart1.rotateAngleZ = -par3;
      this.LWPart2.rotateAngleZ = -par3;
      this.LWPart3.rotateAngleZ = -par3;
      this.LWPart4.rotateAngleZ = -par3;
      this.LWPart5.rotateAngleZ = -par3;
      this.LWPart6.rotateAngleZ = -par3;
      this.LWPart7.rotateAngleZ = -par3;
      this.LWWeb1.rotateAngleZ = -par3;
      this.LWWeb2.rotateAngleZ = -par3;
      this.LWWeb3.rotateAngleZ = -par3;
      this.LWWeb4.rotateAngleZ = -par3;
      this.LWWeb5.rotateAngleZ = -par3;
      this.LWWeb6.rotateAngleZ = -par3;*/
  }
  

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
	  model.rotateAngleX = x;
	  model.rotateAngleY = y;
	  model.rotateAngleZ = z;
  }
}